"""
This file will be autogenerated by when installing by distutils
"""

import os.path

splits = [
    os.path.dirname(os.path.abspath(__file__)), 
    os.path.pardir, os.path.pardir, 
    'data'
    ]

data_dir = os.path.join(*splits)
pixmaps_dir = os.path.join(data_dir, 'pixmaps')

__all__ = ['data_dir', 'pixmaps_dir']
